export const SHORT_MOVIE_DURATION = 40;

export const DESKTOP_BREAKPOINT = 993;
export const TABLET_BREAKPOINT = 481;

export const FIRST_RENDER_MOVIES_COUNT_DESKTOP = 12;
export const FIRST_RENDER_MOVIES_COUNT_TABLET = 8;
export const FIRST_RENDER_MOVIES_COUNT_MOBILE = 5;

export const LOAD_MORE_MOVIES_COUNT_DESKTOP = 3;
export const LOAD_MORE_MOVIES_COUNT_TABLET = 2;
export const LOAD_MORE_MOVIES_COUNT_MOBILE = 1;
